blank_issues_enabled: true
contact_links:
  - name: Questions and discussions
    url: https://github.com/MaxAndreev27/typescript-freeman/discussions
    about: Please use this section for general questions and discussions.
